create table if not exists public.vendedor (
  id bigint generated by default as identity primary key,
  nombre text not null,
  moneda text not null,
  descripcion text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.comentario (
  id bigint generated by default as identity primary key,
  "idVendedor" bigint not null references public.vendedor(id) on delete cascade,
  nombre text not null default 'Anonimo',
  comentario text not null,
  calificacion smallint not null check (calificacion between 1 and 5),
  crypto text,
  created_at timestamptz not null default now()
);

create index if not exists comentario_vendedor_idx
  on public.comentario ("idVendedor");

alter table public.vendedor enable row level security;
alter table public.comentario enable row level security;

grant select, insert on public.vendedor to anon, authenticated;
grant select, insert on public.comentario to anon, authenticated;

drop policy if exists "Public can read sellers" on public.vendedor;
create policy "Public can read sellers"
  on public.vendedor for select to anon, authenticated using (true);

drop policy if exists "Public can register sellers" on public.vendedor;
create policy "Public can register sellers"
  on public.vendedor for insert to anon, authenticated with check (true);

drop policy if exists "Public can read reviews" on public.comentario;
create policy "Public can read reviews"
  on public.comentario for select to anon, authenticated using (true);

drop policy if exists "Public can post reviews" on public.comentario;
create policy "Public can post reviews"
  on public.comentario for insert to anon, authenticated with check (true);